### ISSUE TITLE
Mission does not start

### ISSUE THREAD

**Issue by Daandeve** [lfuelling/esx_redpill#13]
**Describe the bug**
No marker at mission start. When I go to the mission start nothing happens, no errors in the console.

**To Reproduce**
1. Go to Mission start (Fort Zancudo)

**Expected behavior**
Mission should start.

**Screenshots**
-

**Setup (please complete the following information):**
 - Plugin Version 1cd58aabe654dac0660b7a2f4522a10125b25d36

**Additional context**
-

**Comment by lfuelling** [comment]
Hi, 
did you make sure you start the plugin in your `server.cfg`?

Also, the mission start is *inside* the Fort Zancudo elevator. Make sure that you step inside it and there is a blue marker inside. The doors should open as soon as you are in ~2m range of the elevator.

If it still doesn't work please reply and wait a bit I'll probably have time to check this on the weekend.

**Comment by Daandeve** [comment]
Yeah, the plugin is started. No errors in the console, and no blue marker in the elevator

**Comment by lfuelling** [comment]
Do you have esx installed?

**Comment by Daandeve** [comment]
Yup, I installed all the requirements

**Comment by lfuelling** [comment]
Okay, please give me some time to look into it :)

**Comment by lfuelling** [comment]
Hi could you please try out the latest release and see if it works now?

**Comment by lfuelling** [comment]
Hi @Daandeve, I found the issue! 

I'll release the fix later today :)

**Comment by Daandeve** [comment]
Okay!
I will test it when you release it :)

**Comment by lfuelling** [comment]
@Daandeve it was "fixed" (for me) in v0.0.6 please let me know if it works for you.

**Comment by Daandeve** [comment]
Confirmed the issue is fixed, Thanks 😄!
